<div class="box">
    <div class="formContainer">
        <div class="title-login">Login Admin</div>
        <div class="content">
            <form action="<?php echo $this->getUrl('admin/user/login') ?>" method="post">

                    <div class="input-box">
                        <span class="details" for="admin_email">E-mail</span>
                        <input type="email" placeholder="Enter E-mail" id="admin_email" name="admin[admin_email]"
                            value="" required>
                    </div>

                    <div class="input-box">
                        <span class="details" for="password">Password</span>
                        <input type="password" placeholder="Enter Password" id="password"
                            name="admin[password]" value="" required>
                    </div>

                <div class="button">
                    <input type="submit" value="Submit" name = "Submit">
                </div>
            </form>
        </div>
    </div>
</div>