<!-- Start Hero Section -->
<div class="hero">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-5">
                <div class="intro-excerpt">
                    <h1>Cart</h1>
                </div>
            </div>
            <div class="col-lg-7">

            </div>
        </div>
    </div>
</div>
<!-- End Hero Section -->



<div class="untree_co-section before-footer-section">
    <div class="container">
        <div class="row mb-5">
            <div class="site-blocks-table">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="product-thumbnail">Image</th>
                            <th class="product-name">Product</th>
                            <th class="product-price">Price</th>
                            <th class="product-quantity">Quantity</th>
                            <th class="product-total">Total</th>
                            <th class="product-remove">update</th>
                            <th class="product-remove">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $subTotal = 0;
                        $taxnumber = 8;
                        $tax = 0;
                        $grandTotal = 0;
                        foreach ($this->getItemList() as $item) {
                            $productList = $this->getProductList($item->getProductId());
                            foreach ($productList as $product) {
                                ?>
                                <tr>
                                    <td class="product-thumbnail">
                                        <img src="<?php echo Mage::getImagePath("banner/" . $product->getImageLink()) ?>"
                                            alt="Image" class="img-fluid">
                                    </td>
                                    <td class="product-name">
                                        <h2 class="h5 text-black">
                                            <?php echo $product->getName() ?>
                                        </h2>
                                    </td>
                                    <td>
                                        <?php echo "₹" . $product->getPrice() ?>
                                    </td>
                                    <form action="<?php echo $this->getUrl('sales/quote/update') ?>" method="post">
                                        <td>
                                            <div class="input-group mb-3 d-flex align-items-center quantity-container"
                                                style="max-width: 100px;">
                                                <input type="text" name="upd_cart[quote_id]"
                                                    value="<?php echo $item->getQuoteId(); ?>" hidden>
                                                <input type="text" name="upd_cart[item_id]"
                                                    value="<?php echo $item->getItemId(); ?>" hidden>
                                                <input type="text" name="upd_cart[product_id]"
                                                    value="<?php echo $product->getProductId(); ?>" hidden>
                                                <input type="number" class="form-control text-center quantity-amount"
                                                    name="upd_cart[qty]" value="<?php echo $item->getQty(); ?>"
                                                    style="border-radius: 10px;">

                                            </div>

                                        </td>
                                        <td>
                                            <?php echo "₹" . $item->getRowTotal() ?>
                                        </td>
                                        <td>
                                            <button type="submit" name="submit" class="update"><img
                                                    src="<?php echo Mage::getImagePath("banner/updated.png"); ?>" alt="Image"
                                                    class="img-fluid"></button>
                                        </td>
                                    </form>
                                    <td><a href="<?php echo $this->getUrl('sales/quote/delete/') . '?quote_id=' . $item->getQuoteId() . '&item_id=' . $item->getItemId(); ?>"
                                            class="btn btn-black btn remove"><img
                                                src="<?php echo Mage::getImagePath("banner/remove.png"); ?>" alt="Image"
                                                class="img-fluid"></a></td>
                                </tr>
                                <?php
                            }
                            $subTotal += $item->getRowTotal();
                            if ($taxnumber) {
                                $tax = round($subTotal / $taxnumber, 2);
                                $grandTotal = $subTotal + $tax;
                            }
                        }
                        ?>

                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-6">
                        <a href="<?php echo $this->getUrl('catalog/product/view') ?>"><button
                                class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="text-black h4" for="coupon">Coupon</label>
                        <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                        <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-black">Apply Coupon</button>
                    </div>
                </div>
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">
                                    <?php echo "₹" . $subTotal ?>
                                </strong>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">
                                    <?php echo "₹" . $grandTotal ?>
                                </strong>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a href="<?php echo $this->getUrl('cart/checkout/index') ?>"><button
                                        class="btn btn-black btn-lg py-3 btn-block">Proceed To Checkout</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>