<?php 
$data = $this->getProduct();
$categoryModel = Mage::getModel('catalog/category');
$categorys = $categoryModel->getCategoryIdName();
$selectedCategory = $categoryModel->getCategoryNameById($categorys, $data);
?>
<div class="box">
    <div class="formContainer">
        <div class="title">Product Information</div>
        <div class="content">
            <form action="<?php echo $this->getUrl('admin/catalog_product/save') ?>" method="post">
                <div class="user-details">
                    <input type="hidden" placeholder="Enter Product ID" id="product_id"
                        name="catalog_product[product_id]" value="<?php echo $data->getProductId() ?>">
                    <div class="input-box">
                        <span class="details" for="sku">SKU</span>
                        <input type="text" placeholder="Enter SKU" id="sku" name="catalog_product[sku]"
                            value="<?php echo $data->getSku() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="name">Name</span>
                        <input type="text" placeholder="Enter Product Name" id="name" name="catalog_product[name]"
                            value="<?php echo $data->getName() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="color">Color</span>
                        <select id="color" name="catalog_product[color]" class="input-box" required>
                            <?php
                            $color = ["--Select--", "Red", "Green", "Pink", "Blue", "Gray", "Black", "White"];

                            foreach ($color as $col) {
                                echo '<option value="' . $col . '" ' . (($data->getColor() == $col) ? 'selected' : '') . '>' . $col . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                    <div class="input-box-1" style="justify-content:left">
                        <span class="details" for="size">Size</span><br>
                        <input type="radio" id="small_type" name="catalog_product[size]" value="Small" <?php echo (($data->getSize() == "Small") ? 'Checked' : '')?>>
                        <span for="small_type"class="details_box">Small</span>
                        <input type="radio" id="medium_type" name="catalog_product[size]" value="Medium" <?php echo (($data->getSize() == "Medium") ? 'Checked' : '')?>>
                        <span for="medium_type"class="details_box">Medium</span>
                        <input type="radio" id="large_type" name="catalog_product[size]" value="Large" <?php echo (($data->getSize() == "Large") ? 'Checked' : '')?>>
                        <span for="large_type"class="details_box">Large</span>
                    </div>
                    <div class="input-box">
                        <span class="details" for="description">Description</span>
                        <input type="text" placeholder="Enter Description" id="description"
                            name="catalog_product[description]" value="<?php echo $data->getDescription() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="image_link">Image Link</span>
                        <input type="text" placeholder="Enter Image Link" id="image_link"
                            name="catalog_product[image_link]" value="<?php echo $data->getImageLink() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="link">Link</span>
                        <input type="text" placeholder="Enter Link" id="link" name="catalog_product[link]"
                            value="<?php echo $data->getLink() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="category_id">Category Id</span>
                        <select id="category_id" name="catalog_product[category_id]" class="input-box" required>
                            <?php
                            foreach ($categorys as $cat) {
                                echo '<option value="' . $cat . '"' . (($selectedCategory == $cat) ? 'selected' : '') . '>' . $cat . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                    <div class="input-box">
                        <span class="details" for="price">Price</span>
                        <input type="text" placeholder="Enter Price" id="price" name="catalog_product[price]"
                            value="<?php echo $data->getPrice() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="mfr_cost">Manufacturer Cost</span>
                        <input type="text" placeholder="Enter Manufacturer Cost" id="mfr_cost"
                            name="catalog_product[mfr_cost]" value="<?php echo $data->getMfrCost() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="shipping_cost">Shipping Cost </span>
                        <input type="text" placeholder="Enter Shipping Cost" id="shipping_cost"
                            name="catalog_product[shipping_cost]" value="<?php echo $data->getShippingCost() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="total_cost">Total Cost </span>
                        <input type="text" placeholder="Enter Total Cost" id="total_cost"
                            name="catalog_product[total_cost]" value="<?php echo $data->getTotalCost() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="margin_percentage">Margin Percentage</span>
                        <input type="text" placeholder="Enter Margin Percentage" id="margin_percentage"
                            name="catalog_product[margin_percentage]" value="<?php echo $data->getMarginPercentage() ?>"
                            required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="min_price">MiniMum Price</span>
                        <input type="text" placeholder="Enter MiniMum Price" id="min_price"
                            name="catalog_product[min_price]" value="<?php echo $data->getMinPrice() ?>" required>
                    </div>
                    <div class="input-box">
                        <span class="details" for="status">Status</span>
                        <select id="status" name="catalog_product[status]" class="input-box" required>
                            <option value="">---select---</option>
                            <option value="1" <?php echo (($data->getStatus()  == "Enabled") ? 'selected' : '')?>>Enabled</option>
                            <option value="0" <?php echo (($data->getStatus()  == "Disabled") ? 'selected' : '')?>>Disabled</option>
                        </select>
                    </div>
                </div>
                <div class="button">
                    <input type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>