<?php 
$productCollection = $this->showList();
$categoryModel = Mage::getModel('catalog/category');
$categoryNames = $categoryModel->getCategoryIdName();
?>
<div class="box">
    <div class="container-list">
        <div class="add">
            <div class="title">Product Information</div>
            <a href='<?php echo $this->getUrl('admin/catalog_product/form') ?>'>
                <button class="add_btn">Add</button>
            </a>
        </div>
        <table>
            <tr>
                <!-- <th width='200vh'>Product ID</th> -->
                <th width='200vh'>Product Name</th>
                <th width='200vh'>SKU</th>
                <th width='200vh'>Category</th>
                <th width='200vh'>Edit</th>
                <th width='200vh'>Delete</th>
            </tr>

            <?php
            foreach ($productCollection->getData() as $product) {
                $selectedCategory = $categoryModel->getCategoryNameById($categoryNames, $product);
                // echo "<tr><td class = 'column'>";
                // echo $product->getProductId();
                echo "<td class = 'column'>";
                echo $product->getName();
                echo "</td><td class = 'column'>";
                echo $product->getSku();
                echo "</td><td class = 'column'>";
                echo $selectedCategory;
                echo "</td>";
                ?>
                <td align='center' class='button'>
                    <a
                        href='<?php echo $this->getUrl('admin/catalog_product/form/') ?>?id=<?php echo $product->getProductId() ?>'>
                        <button class='upd'>Edit</button>
                    </a>
                </td>
                
                <td align='center' class='button'> <a
                        href='<?php echo $this->getUrl('admin/catalog_product/delete/') ?>?id=<?php echo $product->getProductId() ?>'>
                        <button class='del'>Delete</button>
                    </a>
                </td>
                </tr>
                <?php
            }
            ?>
        </table>
    </div>
</div>