<?php
$cartData = $this->getCartData();
$id = $this->getRequest()->getQueryData('id');
$productCollection = $this->showList();
?>
<div class="small-container single-product">
    <?php foreach ($productCollection->getData() as $product) { ?>
        <div class="row">
            <div class="col-2">
                <img src="<?php echo Mage::getImagePath($product->getImageLink()) ?>" alt="" id="Productimg" class="product-img">
                <div class="small-img-row">
                    <div class="small-img-col">
                        <img src="<?php echo Mage::getImagePath("gallery-1.jpg") ?>" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="<?php echo Mage::getImagePath("gallery-2.jpg") ?>" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="<?php echo Mage::getImagePath("gallery-3.jpg") ?>" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="<?php echo Mage::getImagePath("gallery-4.jpg") ?>" width="100%" class="small-img">
                    </div>
                </div>

            </div>
            <div class="col-2">
                <p>Home / T-Shirt</p>
                <h1>
                    <?php echo $product->getName(); ?>
                </h1>
                <h4>
                    <?php echo "₹" . $product->getPrice() ?>
                </h4>
                <select>
                    <option>Select Size</option>
                    <option>XXL</option>
                    <option>XL</option>
                    <option>Large</option>
                    <option>Medium</option>
                    <option>Small</option>
                </select>

                <select>
                    <option>Color</option>
                    <option>XXL</option>
                    <option>XL</option>
                    <option>Large</option>
                    <option>Medium</option>
                    <option>Small</option>
                </select>

                <form action="<?php echo $this->getUrl('sales/quote/add/')?>" method="post">
                    <input type="text" name="cart[product_id]" value="<?php echo $product->getProductId() ?>" hidden>
                    <input type="number" value="1" name="cart[qty]">
                    <button type="submit" name="Submit" value="Add To cart" class="add-btn">Add To cart</button>
                </form>
                <!-- <a href="<?php //echo $this->getUrl('sales/quote/add/') . '?id=' . $product->getProductId() ?>"
                    class="add-btn">Add To cart</a> -->
                <h3>Product Details</h3>
                <br>
                <p>
                    <?php echo $product->getDescription(); ?>
                </p>
            </div>
        </div>
    <?php } ?>
</div>

<script>
    var Productimg = document.getElementById("Productimg");
    var SmallImg = document.getElementsByClassName("small-img");

    SmallImg[0].onclick = function () {
        Productimg.src = SmallImg[0].src;
    }
    SmallImg[1].onclick = function () {
        Productimg.src = SmallImg[1].src;
    }
    SmallImg[2].onclick = function () {
        Productimg.src = SmallImg[2].src;
    }
    SmallImg[3].onclick = function () {
        Productimg.src = SmallImg[3].src;
    }
</script>