<?php $productCollection = Mage::getModel("catalog/category")->getCollection(); ?>
<div class="box">
    <div class="container-list">
        <div class="add">
            <div class="title">Category Information</div>
            <a href='<?php echo $this->getUrl('admin/catalog_category/form') ?>'>
                <button class="add_btn">Add</button>
            </a>
        </div>
        <table>
            <tr>
                <!-- <th width='200vh'>Category ID</th> -->
                <th width='200vh'>Category Name</th>
                <th width='200vh'>Status</th>
                <th width='200vh'>Edit</th>
                <th width='200vh'>Delete</th>
            </tr>

            <?php
            foreach ($productCollection->getData() as $product) {
                echo "</td><td class = 'column'>";
                echo $product->getCategoryName();
                echo "</td><td class = 'column'>";
                echo $product->getStatus();
                echo "</td>";
                ?>
                <td align='center' class='button'>
                    <a href='
                        <?php echo $this->getUrl('admin/catalog_category/form/') ?>?id=<?php echo $product->getCategoryId() ?>'>
                        <button class='upd'>Edit</button>
                    </a>
                </td>
                <td align='center' class='button'>
                    <a href='
                        <?php echo $this->getUrl('admin/catalog_category/delete/') ?>?id=<?php echo $product->getCategoryId() ?>'>
                        <button class='del'>Delete</button>
                    </a>
                </td>
                </tr>
                <?php
            }
            ?>
        </table>
    </div>
</div>