<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .footer {
            background: #000;
            color: #8a8a8a;
            font-size: 14px;
            padding: 20px 0 20px;
        }

        .footer p {
            color: #8a8a8a;
        }

        .footer h3 {
            color: #fff;
            margin-bottom: 20px;
        }

        .footer-col-1,
        .footer-col-2,
        .footer-col-3,
        .footer-col-4 {
            min-width: 250px;
            margin-bottom: 20px;
        }

        .footer-col-1 {
            flex-basis: 30%;
        }

        .footer-col-2 {
            flex: 1;
            text-align: center;
        }

        .footer-col-2 img {
            width: 150px;
            margin-bottom: 20px;
        }

        .footer-col-3,
        .footer-col-4 {
            flex-basis: 12%;
            text-align: center;
        }

        ul {
            list-style-type: none;
        }

        .app-logo {
            margin-top: 20px;
        }

        .app-logo img {
            width: 150px;
        }

        .footer hr {
            border: none;
            background: #b5b5b5;
            height: 1px;
            margin: 20px 0;
        }

        .Copyright {
            text-align: center;
        }

        .menu-icon {
            width: 28px;
            margin-left: 20px;
            display: none;
        }
    </style>
</head>

<body>
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>Download Our App</h3>
                    <p>Download App for Android and ios mobile phone.</p>
                    <div class="app-logo">
                        <img src="..\MVC\app\code\Local\images/play-store.png" alt="">
                        <img src="..\MVC\app\code\Local\images/app-store.png" alt="">
                    </div>
                </div>
                <div class="footer-col-2">
                    <img src="..\MVC\app\code\Local\images/logo1.png">
                    <p>Our Purpose Is To Sustainably Make the Pleasure <br> and Benefits of Sports Accessible to the
                        Many.</p>
                </div>
                <div class="footer-col-3">
                    <h3>Useful Links</h3>
                    <ul>
                        <li>Coupons</li>
                        <li>Blog Post</li>
                        <li>Return Policy</li>
                        <li>Join Affiliate</li>
                    </ul>
                </div>
                <div class="footer-col-4">
                    <h3>Follow Us</h3>
                    <ul>
                        <li>Facebook</li>
                        <li>Twitter</li>
                        <li>Instagram</li>
                        <li>YouTube</li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
    </div>
</body>

</html>