<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <img src="<?php echo Mage::getImagesUrl('logo.png') ?>" width="125px">
            </div>
            <nav>
                <ul id="MenuItems">
                    <li>
                        <a href="<?php echo $this->getUrl('') ?>">
                            Home
                        </a>
                    </li>

                    <li>
                        <a href="<?php echo $this->getUrl('admin/catalog_product/form/') ?>">
                            Product Form
                        </a>
                    </li>

                    <li>
                        <a href="<?php echo $this->getUrl('admin/catalog_product/list/') ?>">
                            Product List
                        </a>
                    </li>

                    <li>
                        <a href="<?php echo $this->getUrl('admin/catalog_category/form/') ?>">
                            Category Form
                        </a>
                    </li>
                    
                    <li>
                        <a href="<?php echo $this->getUrl('admin/catalog_category/list/') ?>">
                            Category List
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</body>

</html>