<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product</title>
</head>

<body>
    <div class="box">
        <div class="formContainer">
            <div class="title">Product Information</div>
            <div class="content">
                <form action="<?php echo $this->getUrl('catalog/product/save') ?>" method="post">
                    <div class="user-details">
                        <div class="input-box">
                            <span class="details" for="product_id">Product ID</span>
                            <input type="text" placeholder="Enter Product ID" id="product_id" name="ccc_product[product_id]"
                                value="">
                        </div>
                        <div class="input-box">
                            <span class="details" for="sku">SKU</span>
                            <input type="text" placeholder="Enter SKU" id="sku" name="ccc_product[sku]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="name">Name</span>
                            <input type="text" placeholder="Enter Product Name" id="name"
                                name="ccc_product[name]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="color">Color</span>
                            <select id="color" name="ccc_product[color]" class="input-box" required>
                                <?php
                                $color = ["--Select--", "Red", "Green", "Pink", "Blue", "Gray", "Black", "White"];

                                foreach ($color as $col) {
                                    echo '<option value="' . $col . '" >' . $col . '</option>';
                                }
                                ?>
                            </select>
                        </div>
                        <div class="input-box-1" style="justify-content:left">
                            <span class="details" for="size">size</span><br>
                            <!-- <input type="radio" id="small_type" name="ccc_product[size]" value="Small">
                            <span for="small_type">Small</span><br> -->
                            <input type="radio" id="medium_type" name="ccc_product[size]" value="Medium">
                            <span for="medium_type">Medium</span><br>
                            <input type="radio" id="large_type" name="ccc_product[size]" value="Large">
                            <span for="large_type">Large</span>
                        </div>
                        <div class="input-box">
                            <span class="details" for="description">Description</span>
                            <input type="text" placeholder="Enter Description" id="description"
                                name="ccc_product[description]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="image_link">Image Link</span>
                            <input type="text" placeholder="Enter Image Link" id="image_link"
                                name="ccc_product[image_link]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="link">Link</span>
                            <input type="text" placeholder="Enter Link" id="link"
                                name="ccc_product[link]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="category_id">category_id</span>
                            <select id="category_id" name="ccc_product[category_id]" class="input-box" required>
                                <?php
                                $categories = ["--Select--", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

                                foreach ($categories as $cat) {
                                    echo '<option value="' . $cat . '" >' . $cat . '</option>';
                                }
                                ?>
                            </select>
                        </div>
                        <div class="input-box">
                            <span class="details" for="price">Price</span>
                            <input type="text" placeholder="Enter Price" id="price" name="ccc_product[price]" value=""
                                required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="mfr_cost">Manufacturer Cost</span>
                            <input type="text" placeholder="Enter Manufacturer Cost" id="mfr_cost"
                                name="ccc_product[mfr_cost]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="shipping_cost">Shipping Cost </span>
                            <input type="text" placeholder="Enter Shipping Cost" id="shipping_cost"
                                name="ccc_product[shipping_cost]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="total_cost">Total Cost </span>
                            <input type="text" placeholder="Enter Shipping Cost" id="total_cost"
                                name="ccc_product[total_cost]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="margin_percentage">Margin Percentage</span>
                            <input type="text" placeholder="Enter Margin Percentage" id="margin_percentage"
                                name="ccc_product[margin_percentage]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="min_price">MiniMum Price</span>
                            <input type="text" placeholder="Enter MiniMum Price" id="min_price"
                                name="ccc_product[min_price]" value="" required>
                        </div>
                        <div class="input-box">
                            <span class="details" for="status">Status</span>
                            <select id="status" name="ccc_product[status]" class="input-box" required>
                                <option value="">---select---</option>
                                <option value="Enabled">Enabled</option>
                                <option value="Disabled">Disabled</option>
                            </select>
                        </div>
                    </div>
                    <div class="button">
                        <input type="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>