<?php $data = $this->getTempconverter();?>
<div class="box">
    <div class="formContainer">
        <div class="title">Temprature Converter</div>
        <div class="content">
            <form action=<?php  echo $this->getUrl('admin/tempconverter_index/save') ?> method="post">
                <div class="user-details">
                      
                    <div class="input-box">
                        <label for="user_name" class="details">User Name</label>
                        <input type="text" class="form-control" id="user_name" name="tempconverter[user_name]"
                            placeholder="Enter User Name" value ="<?php echo $data->getUserName(); ?>">
                    </div>
                    <div class="input-box">
                        <label for="temprature" class="details">Temprature</label>
                        <input type="text" class="form-control" id="temprature" name="tempconverter[temprature]"
                            placeholder="Enter Temprature" value ="<?php echo $data->getTemprature(); ?>">
                    </div>
                    <div class="input-box">
                        <label for="unit" class="details">Unit</label>
                            <select name="tempconverter[unit]" id="unit">
                                <option>---select---</option>
                                <option <?php echo (($data->getUnit()  == "Celsius") ? 'Celsius' : '') ?> value="Celsius">Celsius</option>
                                <option <?php echo (($data->getUnit()  == "Farenheit") ? 'Farenheit' : '') ?> value="Farenheit">Farenheit</option>
                                <option <?php echo (($data->getUnit()  == "Kelvin") ? 'Kelvin' : '') ?> value="Kelvin">Kelvin</option>
                            </select>
                    </div>
                    <div class="input-box">
                        <label for="convert_unit" class="details">Convert Unit</label>
                            <select name="tempconverter[convert_unit]" id="convert_unit">
                                <option>---select---</option>
                                <option <?php echo (($data->getConvertUnit()  == "Celsius") ? 'Celsius' : '') ?> value="Celsius">Celsius</option>
                                <option <?php echo (($data->getConvertUnit()  == "Farenheit") ? 'Farenheit' : '') ?> value="Farenheit">Farenheit</option>
                                <option <?php echo (($data->getConvertUnit()  == "Kelvin") ? 'Kelvin' : '') ?> value="Kelvin">Kelvin</option>
                            </select>
                    </div>
                </div>
                <div class="button">
                    <input type="submit" value="Submit" name="submit">
                </div>
            </form>
        </div>
    </div>
</div>