<div class="box">
<div class="container-list">
    <div class="add">
        <div class="title">Temprature Information</div>
        <a href='<?php echo $this->getUrl('admin/tempconverter_index/form/') ?>'>
            <button class="add_btn">Add</button>
        </a>
    </div>
    <table>
        <tr>
            <th width='200vh'>User Name</th>
            <th width='200vh'>Temprature</th>
            <th width='200vh'>Convert Temprature</th>
            <th width='200vh'>UPDATE</th>
            <th width='200vh'>DELETE</th>
        </tr>
    <?php foreach ($this->getCollectionsData() as $temp):?>
        <tr>
            <td class = 'column'>
                <?php echo ($temp->getUserName()); ?>
            </td>
            <td class = 'column'>
                <?php echo ($temp->getTemprature()) ." ".($temp->getUnit()); ?>
            </td>
            <td class = 'column'>
                <?php echo ($temp->getTemprature())." ".($temp->getUnit()); ?>
            </td>
            <td class = 'column'>
                <a href="<?php echo $this->getUrl('admin/tempconverter_index/form/') . '?id=' . $temp->getId();?>"id="update"><button class='upd'>Edit</button></a>
            </td>
            <td class = 'column'>
                <a href="<?php echo $this->getUrl('admin/tempconverter_index/delete/') . '?id=' .$temp->getId();?>"id="delete"><button class='del'>Delete</button></a>
            </td>
        </tr>
        <?php endforeach;?>
    </table>
</div>
</body>
</html>