<?php
$productCollection = Mage::getModel("banner/banner")->getCollection();
$imageList = [];
foreach ($productCollection->getData() as $value) {
    $imageList[] = $value->getBannerImage();
}
?>
<div class="row">
    <div class="col-2">
        <h1>Give Your Workout <br> A New Style!</h1>
        <p>Success isn't always about greatness. It's about consistency. <br> Consistent hard work gain
            success. Greatness will come.</p>
        <a href="" class="btn">Explore Now &#8594;</a>
    </div>
    <div class="col-2">
        <img src="<?php echo Mage::getImagePath($imageList[0]) ?>" alt="">
    </div>
</div>