<div class="container relative">
    <?php foreach ($this->orderIdd() as $_orderId) { ?>
        <div class="content">
            <div class="boxes">Order Id:
                <?php echo $_orderId->getId() ?>
            </div>
            <?php foreach ($this->items($_orderId->getId()) as $_item) { ?>

                <div class="boxes">
                    <div class="data">
                        <div class="product-title">
                            <?php echo $_item->getProductName() ?>
                            <div class="product-image">
                                <img src="<?php echo Mage::getImagePath("/banner/" . $this->product($_item->getProductId())->getImageLink()); ?>"
                                    alt="Product Image">
                            </div>

                        </div>
                    </div>
                    <div class="data">
                        <div class="order-info">
                            <div class="order-no">Order Number:
                                <?php echo $_orderId->getOrderNumber() ?>
                            </div>
                            <div class="order-qty">Quantity:
                                <?php echo $_item->getQty() ?>
                            </div>
                            <div class="order-price">Price: $
                                <?php echo $this->product($_item->getProductId())->getPrice(); ?>
                            </div>
                            <div class="order-total">Total: $
                                <?php echo $_orderId->getGrandTotal() ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
</div>